version: '3.9'
x-scala-dfs-common:
  &scala-dfs-common
  image: scala:2.13.6
  build:
    context: .
    dockerfile: ./Dockerfile

services:
  scala-rmi-master:
    <<: *scala-dfs-common
    ports:
      - 1099:1099
    volumes:
      - ./master/target/scala-2.13/master_2.13.6-0.1.0-SNAPSHOT.jar:/code/master_2.13.6-0.1.0-SNAPSHOT.jar
      - ./node/target/scala-2.13/node_2.13.6-0.1.0-SNAPSHOT.jar:/code/node_2.13.6-0.1.0-SNAPSHOT.jar
      - ./policies/master.policy:/code/master.policy
      - ./data:/code/data
    command: scala -Djava.rmi.server.codebase=file:/code/node_2.13.6-0.1.0-SNAPSHOT.jar -Djava.security.policy=master.policy master_2.13.6-0.1.0-SNAPSHOT.jar

  scala-rmi-node1:
    <<: *scala-dfs-common
    ports:
      - 10991:10991
    volumes:
      - ./master/target/scala-2.13/master_2.13.6-0.1.0-SNAPSHOT.jar:/code/master_2.13.6-0.1.0-SNAPSHOT.jar
      - ./node/target/scala-2.13/node_2.13.6-0.1.0-SNAPSHOT.jar:/code/node_2.13.6-0.1.0-SNAPSHOT.jar
      - ./policies/node.policy:/code/node.policy
      - ./data:/code/data
    command: scala -Djava.rmi.server.codebase=file:/code/master_2.13.6-0.1.0-SNAPSHOT.jar -Djava.security.policy=node.policy node_2.13.6-0.1.0-SNAPSHOT.jar DataNode1 10991
    depends_on:
      - "scala-rmi-master"

  scala-rmi-node2:
    <<: *scala-dfs-common
    ports:
      - 10992:10992
    volumes:
      - ./master/target/scala-2.13/master_2.13.6-0.1.0-SNAPSHOT.jar:/code/master_2.13.6-0.1.0-SNAPSHOT.jar
      - ./node/target/scala-2.13/node_2.13.6-0.1.0-SNAPSHOT.jar:/code/node_2.13.6-0.1.0-SNAPSHOT.jar
      - ./policies/node.policy:/code/node.policy
      - ./data:/code/data
    command: scala -Djava.rmi.server.codebase=file:/code/master_2.13.6-0.1.0-SNAPSHOT.jar -Djava.security.policy=node.policy node_2.13.6-0.1.0-SNAPSHOT.jar DataNode2 10992
    depends_on:
      - "scala-rmi-master"
      - "scala-rmi-node1"

  scala-rmi-node3:
    <<: *scala-dfs-common
    ports:
      - 10993:10993
    volumes:
      - ./master/target/scala-2.13/master_2.13.6-0.1.0-SNAPSHOT.jar:/code/master_2.13.6-0.1.0-SNAPSHOT.jar
      - ./node/target/scala-2.13/node_2.13.6-0.1.0-SNAPSHOT.jar:/code/node_2.13.6-0.1.0-SNAPSHOT.jar
      - ./policies/node.policy:/code/node.policy
      - ./data:/code/data
    command: scala -Djava.rmi.server.codebase=file:/code/master_2.13.6-0.1.0-SNAPSHOT.jar -Djava.security.policy=node.policy node_2.13.6-0.1.0-SNAPSHOT.jar DataNode3 10993
    depends_on:
      - "scala-rmi-master"
      - "scala-rmi-node1"
      - "scala-rmi-node2"

networks:
  default:


